### PR TITLE
Authors perpetuate long debunked attacks on science of evolution, cos…

### PR DESCRIPTION
**Pull request by paxperscientiam**
…mology, etc.

### CODE REVIEW

**Comment by Bubu92** [comment]
Idealo.uk .fr... The company idealo internet GmbH is a price comparison service, no fake news there.

**Comment by paxperscientiam** [comment]
@Bubu92 Are you referring to my commit? My addition was only `0.0.0.0 conservapedia.com`.

That said, @marktron, if you want to nail down the criteria for "fakenews" a bit more, the essay _The Fine Art of Baloney Detection_ by the late great Dr. Carl Sagan can be found [here]("http://www.inf.fu-berlin.de/lehre/pmo/eng/Sagan-Baloney.pdf).

Cheers.

**Comment by Bubu92** [comment]
@paxperscientiam Sorry I was not, it is a misunderstanding. I was just saying that the website "idealo" was blocked. But it has nothing to do with fake news.

**Comment by marktron** [comment]
@paxperscientiam - Thanks for the contribution. Although I don't agree with their approach or viewpoint, I'm not 100% sure I'd categorize conservapedia as "fake news". I'm going to leave this PR open while I give it some more thought. As you correctly pointed out, my definition is pretty squishy and should be nailed down a bit more :)

@Bubu92 - There are no "idealo" websites blocked in my hosts file, perhaps it is being blocked by another hosts file you are using?

**Comment by Bubu92** [comment]
@marktron I understood from my VPN provider, Perfect Privacy, that their Fake News block list is in fact using your list.
"Fake News filter: Block list with known fake news domains using a publicly available filter list hosted on GitHub to which anyone can contribute."

**Comment by StevenBlack** [comment]
Personal opinion: fake news.

Mainly because it fails the test of [neutral point of view](https://en.wikipedia.org/wiki/Wikipedia:Neutral_point_of_view) in clear and obvious ways.  For example, the selection of photographs that illustrate every single article I perused so far.

**Comment by StevenBlack** [comment]
Another factor: user `DavidB4`.  Look at his user page.  This site is garbage.

   http://www.conservapedia.com/User:DavidB4

**Comment by marktron** [comment]
@Bubu92 - There have never been any Idealo sites on my list, so I'm not sure where your VPN got that from. You can see everything my list blocks here: https://github.com/marktron/fakenews/blob/master/fakenews

**Comment by Bubu92** [comment]
Thanks for the info I will let them know!

Also, FYI considering that the need to counter "false information" is real, one can understand the will to act of some. However, in the approach of the newspaper Le Monde with their Décodex tool (http://www.lemonde.fr/verification), what is seen it is not a fight against hoax, but arbitrary, sometimes complacent, sometimes harsh judgments of a team that makes itself judge and party and loses its original purpose, takes advantage of it to settle accounts, condemn what they do not like, instead of condemning what is false. 
Then, Lejendarm (pseudonym) did not appreciate the last gadget and decided to create its own extension for Google's browser:  OpenMind

**Comment by paxperscientiam** [comment]
I was going to suggest a criterion that the site be profiting from fake news, but fake news is fake news. @StevenBlack raises a good point. Why not adopt Wikipedia's "neutral viewpoint" criterion?

Of course, use of neutral viewpoint is fundamental to journalism in general.

**Pull request closed without merging**
